version: '3'
services:
  db:
    networks:
      - heartnet
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:z
    restart: always
  main-app:
    networks:
    - heartnet
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - ./app:/myapp/app:z
      - ./bin:/myapp/bin:z
      - ./config:/myapp/config:z
      - ./db:/myapp/db:z
      - ./lib:/myapp/lib:z
      - ./public:/myapp/public:z
      - ./spec:/myapp/spec:z
    environment:
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
      RAILS_ENV: development
    command: foreman start
    depends_on:
      - db
networks:
  heartnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
